# Generated by Django 2.2.19 on 2021-03-27 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_replie_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replie',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.Thread'),
        ),
    ]
