# Generated by Django 2.2.19 on 2021-03-27 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20210327_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replie',
            name='owner',
            field=models.CharField(default='teste', max_length=150, verbose_name='User Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thread',
            name='owner',
            field=models.CharField(default='Teste', help_text='Title of the thread', max_length=150, verbose_name='User Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(help_text='Title of the thread', max_length=150, verbose_name='Title'),
        ),
    ]
